# Generated by Django 4.1.5 on 2023-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.IntegerField(unique=True),
        ),
    ]
