# Generated by Django 4.0.7 on 2023-01-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_address_uf_alter_address_city_alter_address_country_and_more'),
        ('users', '0005_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='adresses.address'),
        ),
    ]
