# Generated by Django 4.0.7 on 2023-01-03 10:15

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='picture_url',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='imagem'),
            preserve_default=False,
        ),
    ]
