# Generated by Django 4.0.7 on 2023-01-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_book_on_sale_book_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categorys',
            field=models.ManyToManyField(related_name='books', to='books.category'),
        ),
    ]
