# Generated by Django 4.0.7 on 2023-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categorys',
            field=models.ManyToManyField(related_name='books', to='books.category'),
        ),
    ]
