# Generated by Django 4.1.5 on 2023-01-11 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paymount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(max_length=64, null=True)),
                ("status", models.CharField(max_length=64)),
                ("value", models.PositiveSmallIntegerField()),
                ("payment_method", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("link_billet_pdf", models.TextField()),
                ("link_billet_png", models.TextField()),
                (
                    "billet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paymount",
                        to="billets.billet",
                    ),
                ),
            ],
        ),
    ]
