# Generated by Django 4.0.7 on 2023-01-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymount',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
